# Generated by Django 5.0.6 on 2024-05-15 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_stock', models.PositiveIntegerField(verbose_name=0)),
                ('price', models.PositiveIntegerField(verbose_name=3500)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_month', models.PositiveIntegerField(verbose_name=4)),
                ('date_day', models.PositiveIntegerField(verbose_name=12)),
                ('date_year', models.PositiveIntegerField(verbose_name=2024)),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_cycling_store_app.customer')),
            ],
        ),
    ]
