# Generated by Django 5.0.6 on 2024-05-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cycling_store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='paid',
            field=models.TextField(null=True),
        ),
    ]
