# Generated by Django 5.0.6 on 2024-05-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cycling_store_app', '0003_alter_customerorder_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.TextField(default='bicycle', max_length=50),
        ),
    ]
