# Generated by Django 5.0.6 on 2024-05-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cycling_store_app', '0004_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.PositiveIntegerField(default=3500),
        ),
    ]
