# Generated by Django 5.0.6 on 2024-05-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cycling_store_app', '0006_customerorder_order_alter_vehicle_number_in_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.TextField(default='black', max_length=50, null=True),
        ),
    ]
