# Generated by Django 5.0.6 on 2024-05-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cycling_store_app', '0007_vehicle_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='date_day',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='date_month',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='date_year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='order',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='order',
            field=models.ManyToManyField(to='django_cycling_store_app.vehicle'),
        ),
    ]
