# Generated by Django 5.0.6 on 2024-05-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_cycling_store_app', '0008_alter_customerorder_date_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorder',
            old_name='order',
            new_name='vehicles_in_order',
        ),
    ]
