# Generated by Django 5.0.6 on 2024-05-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cycling_store_app', '0009_rename_order_customerorder_vehicles_in_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='order_quantity',
            field=models.PositiveIntegerField(default=1, max_length=50),
        ),
    ]
