# Generated by Django 5.0.6 on 2024-05-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cycling_store_app', '0011_alter_customerorder_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='vehicles_in_order',
            field=models.ManyToManyField(null=True, related_name='order', to='django_cycling_store_app.vehicle'),
        ),
    ]
